version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./static:/app/static
      - ./comments/files:/app/files
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    volumes:
      - ./:/app
      - ./comments/static/css:/app/static
      - ./comments/files:/app/files
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  static:
  files: